accounts/urls.py
from django.conf.urls import url

from accounts import views


app_name = "accounts"

urlpatterns = [

    url(r'^accounts/$',
        views.AccountList.as_view(),
        name="account_list"),

    url(r'^(?P<account_slug>[-\w]*)/$',
        views.account_detail,
        name="account_detail"),

    url(r'^(?P<account_slug>[-\w]*)/remove/$',
        views.account_remove,
        name="account_remove"),

    url(r'^(?P<account_slug>[-\w]*)/update/$',
        views.account_update,
        name="account_update"),
]

datasets/urls.py
from django.conf.urls import url

from datasets import views

app_name = "datasets"

urlpatterns = [
    url(r"^new_dataset/$",
        views.new_dataset,
        name="new_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/$",
        views.dataset_detail,
        name="dataset_detail"),

    url(r"^(?P<dataset_slug>[-\w]*)/embed/$",
        views.embed_dataset,
        name="embed_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/sanity/$",
        views.sanity_dataset,
        name="sanity_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/add_keyword/$",
        views.add_keyword_to_dataset,
        name="add_keyword_to_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/remove_keyword/$",
        views.remove_keyword_from_dataset,
        name="remove_keyword_from_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/update/$",
        views.dataset_update,
        name="dataset_update"),

    url(r"^(?P<dataset_slug>[-\w]*)/update/auth/$",
        views.dataset_update_auth,
        name="dataset_update_auth"),

    url(r"^(?P<dataset_slug>[-\w]*)/remove/$",
        views.dataset_remove,
        name="dataset_remove"),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView

from core.forms import CustomUserCreationForm

from main import views


urlpatterns = [

    url(r'^$',
        views.portal,
        name='portal'),

    url(r'^about/$',
        TemplateView.as_view(template_name='about.html'),
        name='about'),

    url(r'^access_denied/$',
        TemplateView.as_view(template_name='access_denied.html'),
        name='access_denied'),

    url(r'^admin/', admin.site.urls),

    url(r'^contact/$',
        TemplateView.as_view(template_name='contact.html'),
        name='contact'),

    url(r'^load_dataset/(?P<pk>[0-9]+)/$',  # this one is tricky
        views.load_dataset,
        name='load_dataset'),

    # should this be part of the accounts app, where I create an account?
    url(r'^register/',
        CreateView.as_view(
            template_name='register.html',
            form_class=CustomUserCreationForm,
            success_url='/login'
        ),
        name='register'),

    # django sign in forms and stuff
    url(r'^', include('django.contrib.auth.urls')),
    #
    # The default urls from django.contrib.auth.urls:
    # ^login/$ [name='login']
    # ^logout/$ [name='logout']
    # ^password_change/$ [name='password_change']
    # ^password_change/done/$ [name='password_change_done']
    # ^password_reset/$ [name='password_reset']
    # ^password_reset/done/$ [name='password_reset_done']
    # ^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/
    #     (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$
    #     [name='password_reset_confirm']
    # ^reset/done/$ [name='password_reset_complete']
    #
    # I also want to put create update delete user views in this part


    # I just removed django rest framework stuff
    # url(r'^api/',
    #    include('api.urls',
    #            namespace='api')),

    url(r'^keywords/',
        include('keywords.urls',
                namespace='keywords')),

    url(r'^',
        include('accounts.urls',
                namespace='accounts')),

    url(r'^(?P<account_slug>[-\w]*)/',
        include('datasets.urls',
                namespace='datasets')),
]

accounts/models.py
from django.urls import reverse
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify

from django.conf import settings

class Account(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    affiliation = models.CharField(max_length=200, null=True, blank=True)
    account_slug = models.SlugField(max_length=50, unique=True, null=True)
    date_added = models.DateTimeField(auto_now=False, auto_now_add=True,
                                      null=True, blank=True)

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        self.account_slug = slugify(self.user)
        super(Account, self).save(*args, **kwargs)

    # super hacky, I should have a better answer than this
    # I will fix it later, but right now it is being used for the json serializer
    def natural_key(self):
        return self.account_slug

    def get_absolute_url(self):
        kwargs = {"account_slug": self.account_slug}
        return reverse("accounts:account_detail", kwargs=kwargs)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_account(sender, instance, created, **kwargs):
    if created:
        Account.objects.create(user=instance)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def save_user_account(sender, instance, **kwargs):
    instance.account.save()

accounts/forms.py
from django import forms

from accounts.models import Account


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["affiliation"]

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView

from accounts.models import Account
from accounts.forms import AccountForm

from datasets.models import Dataset

"""
All these views can probably be refactored into django's class views
they are no longer doing very special things, most of the special things
the views do have been pushed to the main/views.py file. I just need
to figure out how to put page queries from templates into these views
"""

class AccountList(ListView):
    model = Account
    context_object_name = "account_list"
    template_name = "accounts/account_list.html"


@login_required
def account_update(request, account_slug=None):
    account = get_object_or_404(Account, account_slug=account_slug)
    if request.user.id != account.user.id:
        return redirect("access_denied")
    else:
        if request.method == "POST":
            form = AccountForm(request.POST, instance=account)
            if form.is_valid():
                form.save()
                return redirect("accounts:account_detail",
                                account_slug=account.account_slug)
            else:
                return HttpResponse("Error!")
        else:
            form = AccountForm(instance=account)
        template_name = "accounts/account_update.html"
        return render(request, template_name,
                      {"account": account, "form": form})


@login_required
def account_remove(request, account_slug=None):
    # this view actually removes the user model, and everything associated
    # with it
    account = get_object_or_404(Account, account_slug=account_slug)
    if request.user.id != account.user.id:
        return redirect("access_denied")
    else:
        context = {"account": account}
        template_name = "accounts/account_remove.html"
        if request.method == 'POST':
            account.user.delete()
            return redirect('/')
        return render(request, template_name, context)


# this can probably be refactored
def account_detail(request, account_slug=None):
    account = get_object_or_404(Account, account_slug=account_slug)
    d = Dataset.objects.filter(account=account)

    if "q" in request.GET:
        q = request.GET["q"]
        dataset_list = d.filter(
            Q(title__icontains=q) | Q(author__icontains=q)).order_by("title")
    else:
        dataset_list = d.order_by("title")

    template_name = "accounts/account_detail.html"
    return render(request, template_name,
                  context={"account": account, "dataset_list": dataset_list})

templates/accounts/account_ajax.html
<!-- this whole page is extraneous -->
<div class="container-fluid">
  <h2><a href="{{ account.get_absolute_url }}">{{ account }}</a></h2>
  <h3>{{ account.affiliation }}</h3>
  <p>There should be some extra information here, perhaps a description of the account</p>
  <ul id="dataset_list">
    {% if dataset_list %}
      {% for dataset in dataset_list %}
        <li>
          <a href="{{ dataset.get_absolute_url }}">{{ dataset.title }}</a>
        </li>
      {% endfor %}
    {% else %}
      <li>
        This account has no datasets yet
      </li>
    {% endif %}
  </ul>
</div>

templates/accounts/account_detail.html
{% extends "base_portal.html" %}
{% load staticfiles %}

{% block title %}{{ account.user }}{% endblock title %}

{% block breadcrumbs %}
/ <a href="{{ account.get_absolute_url }}" >{{ account.user }}</a>
{% endblock breadcrumbs %}

{% block portal_content %}

{% if account.affiliation %}
<div>
  <p><b>{{ account.user }}'s affiliation:</b> {{ account.affiliation }}</p>
</div>
<hr>
{% endif %}

<div>
  <p>
    <a href="{% url 'datasets:new_dataset' account.account_slug %}">
      Add New Dataset
    </a>
  </p>
  <p>
    <a href="{% url 'accounts:account_update' account.account_slug %}">
      Update Account
    </a>
  </p>
  <p>
    <a href="{% url 'accounts:account_remove' account.account_slug %}">
      Remove Account
    </a>
  </p>
</div>
<hr>
{% endblock portal_content %}

templates/accounts/account_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Accounts{% endblock title %}

{% block breadcrumbs %}
/ <a href="{% url 'accounts:account_list' %}" >accounts</a>
{% endblock breadcrumbs %}

{% block content %}
<h1>Accounts</h1>
<form action="." method="GET">
  <input id="account_query_input" type="text" title="Search Accounts" placeholder="Search Accounts" name="q"/>
</form>
<h5>Accounts: {{ total_accounts }}</h5>
<hr/>
{% for account in account_list %}
<p>
  <a name="account_link" id="{{ account.pk }}" href="{{ account.get_absolute_url }}">
    {{ account.user }}: {{ account.datasets.all|length }} datasets
  </a>
</p>
{% endfor %}
{% endblock content %}

templates/accounts/account_remove.html
{% extends "base.html" %}

{% block title %}Remove Account{% endblock title %}

{% block breadcrumbs %}
/ <a href="{{ account.get_absolute_url }}">{{ account.user }}</a>
/ <a href="{% url 'accounts:account_remove' account.account_slug %}" >remove {{ account.user }}'s account</a>
{% endblock breadcrumbs %}


{% block content %}

  <p>
    <form action="." method="POST">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="Yes, please remove {{ account.user }}"/>
    </form>
  </p>

  <p>
    <a href="{{ account.get_absolute_url }}">
      No, take me back to {{ account.user }}'s page
    </a>
  </p>

{% endblock content %}

templates/accounts/account_update.html
{% extends "base.html" %}

{% block title %}Update {{ account.user }}{% endblock title %}

{% block breadcrumbs %}
/ <a href="{{ account.get_absolute_url }}">{{ account.user }}</a>
/ <a href="{% url 'accounts:account_update' account.account_slug %}" >update {{ account.user }}'s account</a>
{% endblock breadcrumbs %}

{% block content %}

  <p>
    <form action="." method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-default" type="submit" value="Update {{ account.user }}">
    </form>
  </p>
  <h3><a href="{% url 'password_reset' %}">Reset Password</a></h3>

  <p>
    <a href="{{ account.get_absolute_url }}">
      No, take me back to {{ account.user }}'s page
    </a>
  </p>

{% endblock content %}

templates/accounts/account_view.html
{% extends 'base.html' %}

{% block content %}

<h2>Account View</h2>
{% if dataset_list %}
  {% for dataset in dataset_list %}
    {{ dataset.title }}
  {% endfor %}
{% else %}
  This account does not have any datasets yet
{% endif %}

{% endblock content %}