datasets/urls.py
from django.conf.urls import url

from datasets import views

app_name = "datasets"

urlpatterns = [
    url(r"^new_dataset/$",
        views.new_dataset,
        name="new_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/$",
        views.dataset_detail,
        name="dataset_detail"),

    url(r"^(?P<dataset_slug>[-\w]*)/embed/$",
        views.embed_dataset,
        name="embed_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/sanity/$",
        views.sanity_dataset,
        name="sanity_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/add_keyword/$",
        views.add_keyword_to_dataset,
        name="add_keyword_to_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/remove_keyword/$",
        views.remove_keyword_from_dataset,
        name="remove_keyword_from_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/update/$",
        views.dataset_update,
        name="dataset_update"),

    url(r"^(?P<dataset_slug>[-\w]*)/update/auth/$",
        views.dataset_update_auth,
        name="dataset_update_auth"),

    url(r"^(?P<dataset_slug>[-\w]*)/remove/$",
        views.dataset_remove,
        name="dataset_remove"),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView

from core.forms import CustomUserCreationForm

from main import views


urlpatterns = [

    url(r'^$',
        views.portal,
        name='portal'),

    url(r'^about/$',
        TemplateView.as_view(template_name='about.html'),
        name='about'),

    url(r'^access_denied/$',
        TemplateView.as_view(template_name='access_denied.html'),
        name='access_denied'),

    url(r'^admin/', admin.site.urls),

    url(r'^contact/$',
        TemplateView.as_view(template_name='contact.html'),
        name='contact'),

    url(r'^load_dataset/(?P<pk>[0-9]+)/$',  # this one is tricky
        views.load_dataset,
        name='load_dataset'),

    # should this be part of the accounts app, where I create an account?
    url(r'^register/',
        CreateView.as_view(
            template_name='register.html',
            form_class=CustomUserCreationForm,
            success_url='/login'
        ),
        name='register'),

    # django sign in forms and stuff
    url(r'^', include('django.contrib.auth.urls')),
    #
    # The default urls from django.contrib.auth.urls:
    # ^login/$ [name='login']
    # ^logout/$ [name='logout']
    # ^password_change/$ [name='password_change']
    # ^password_change/done/$ [name='password_change_done']
    # ^password_reset/$ [name='password_reset']
    # ^password_reset/done/$ [name='password_reset_done']
    # ^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/
    #     (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$
    #     [name='password_reset_confirm']
    # ^reset/done/$ [name='password_reset_complete']
    #
    # I also want to put create update delete user views in this part


    # I just removed django rest framework stuff
    # url(r'^api/',
    #    include('api.urls',
    #            namespace='api')),

    url(r'^keywords/',
        include('keywords.urls',
                namespace='keywords')),

    url(r'^',
        include('accounts.urls',
                namespace='accounts')),

    url(r'^(?P<account_slug>[-\w]*)/',
        include('datasets.urls',
                namespace='datasets')),
]

datasets/forms.py
from django import forms

from datasets.models import Dataset


class DatasetCreateForm(forms.ModelForm):
    """
    This form will have all the fields that are created by the user,
    and only be used to create datasets
    """
    class Meta:
        model = Dataset

        fields = ["title", "author", "url",
                  "owncloud", "owncloud_instance", "owncloud_path",
                  "public_access", "description",
                  "dataset_user", "dataset_password"]

        widgets = {
            "dataset_user": forms.PasswordInput(),
            "dataset_password": forms.PasswordInput()
        }


class DatasetUpdateForm(forms.ModelForm):
    """
    Until after the initial deployment i am removing "dataset_user" and
    "dataset_password"
    """
    class Meta:
        model = Dataset

        fields = ["title", "author", "url",
                  "public_access", "description"]

        
class DatasetUpdateAuthForm(forms.ModelForm):
    """
    This will only update the dataset_user and the dataset_password fields
    """
    class Meta:
        model = Dataset

        fields = ["dataset_user", "dataset_password",
                  "owncloud", "owncloud_instance", "owncloud_path"]

        widgets = {
            "dataset_user": forms.PasswordInput(),
            "dataset_password": forms.PasswordInput()
        }

datasets/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from accounts.models import Account

from datasets.models import Dataset
from datasets.forms import DatasetCreateForm
from datasets.forms import DatasetUpdateForm
from datasets.forms import DatasetUpdateAuthForm

from keywords.models import Keyword


def dataset_detail(request, account_slug=None, dataset_slug=None):
    """
    In this view I bring in the account and the dataset, and I check to see
    if the dataset is protected by password and username, meaning I will have
    to make the ajax call to the /load_dataset/<pk>/ view. If I don't have to
    do this, I can just use a plain old XMLHttpRequest to get the data, which
    should be faster than getting it through the server.
    """
    account = get_object_or_404(Account, account_slug=account_slug)
    dataset = get_object_or_404(Dataset, dataset_slug=dataset_slug, account=account)
    keyword_list = dataset.keywords.all()

    context = {"account": account,
               "keyword_list": keyword_list,
               "dataset": dataset}
    template_name = "datasets/dataset_detail.html"
    return render(request, template_name, context)

def embed_dataset(request, account_slug=None, dataset_slug=None):
    """
    This is the page that will be embedded into the ZMT's staff pages.
    """
    account = get_object_or_404(Account, account_slug=account_slug)
    dataset = get_object_or_404(Dataset, dataset_slug=dataset_slug, account=account)
    keyword_list = dataset.keywords.all()

    context = {"account": account,
               "keyword_list": keyword_list,
               "dataset": dataset}
    template_name = "datasets/embed_dataset.html"
    response = render(request, template_name, context)

    # here's the important part
    response["Access-Control-Allow-Origin"] = "*"
    response["Access-Control-Allow-Methods"] = "GET, OPTIONS"
    response["Access-Control-Max-Age"] = "43200"
    response["Access-Control-Allow-Headers"] = "X-Requested-With, Content-Type"
    response["X-Frame-Options"] = "ALLOW-FROM https://www.leibniz-zmt.de/"
    
    return response

def sanity_dataset(request, account_slug=None, dataset_slug=None):
    """
    This page is just here so that I know embedding works.
    """
    account = get_object_or_404(Account, account_slug=account_slug)
    dataset = get_object_or_404(Dataset, dataset_slug=dataset_slug, account=account)
    keyword_list = dataset.keywords.all()

    context = {"account": account,
               "keyword_list": keyword_list,
               "dataset": dataset}
    template_name = "datasets/embed_dataset.html"
    response = render(request, template_name, context)

    # here's the important part
    response["Access-Control-Allow-Origin"] = "*"
    response["Access-Control-Allow-Methods"] = "GET, OPTIONS"
    response["Access-Control-Max-Age"] = "43200"
    response["Access-Control-Allow-Headers"] = "X-Requested-With, Content-Type"
    response["X-Frame-Options"] = "ALLOW-FROM https://s3.eu-central-1.amazonaws.com/spatialdatahub-embed-test/"
    
    return response

@login_required
def new_dataset(request, account_slug):
    account = get_object_or_404(Account, account_slug=account_slug)
    if request.user.id != account.user.id:
        return redirect("access_denied")
    else:
        if request.method == "POST":
            form = DatasetCreateForm(request.POST)
            if form.is_valid():
                dataset = form.save(commit=False)
                dataset.account = account
                dataset.save()
                return redirect("datasets:dataset_detail",
                                account_slug=account.account_slug,
                                dataset_slug=dataset.dataset_slug)
        else:
            form = DatasetCreateForm()
            template_name = "datasets/new_dataset.html"
        return render(request,
                      template_name,
                      {"form": form,
                       "account": account})


"""
should the add keyword to dataset and remove keyword from dataset views be
in the keywords app?
"""

@login_required
def add_keyword_to_dataset(request, account_slug=None, dataset_slug=None):
    """ This works. It associates a keyword with a dataset, and if the keyword
        already exists, it simply gets that keyword and associates it with the
        dataset.

        Should this be in the keywords app? I now have to add a remove keywords from
        dataset page as well.
    """
    account = get_object_or_404(Account, account_slug=account_slug)
    dataset = get_object_or_404(Dataset, dataset_slug=dataset_slug, account=account)
    if "kw" in request.POST:
        kw = request.POST["kw"]
        # this isn't working. I think that get or create is not meant for many to many
        # stuff. What is happening is if the keyword already exists in the database,
        # the get or create is failing, becaues it's checking against the keywords
        # associated with the datset, and not the database. So it tries to make the
        # keyword, but then the process fails because of unique keyword constraints.

        # This needs an if statement that checks if the keyword already exists, and
        # if it doesn't, create it and associate it with the dataset
        # if it does just associate it with the dataset
        keyword_lower = kw.lower()

        try:
            n = Keyword.objects.get(keyword=keyword_lower)
            dataset.keywords.add(n)
        except ObjectDoesNotExist:
            dataset.keywords.create(keyword=keyword_lower)

        return redirect("datasets:dataset_detail",
                        account_slug=account.account_slug,
                        dataset_slug=dataset.dataset_slug)
    
    context = {"account": account, "dataset": dataset}
    template_name = "datasets/add_keyword_to_dataset.html"
    return render(request, template_name, context)

@login_required
def remove_keyword_from_dataset(request, account_slug=None, dataset_slug=None):
    """ This works. It associates a keyword with a dataset, and if the keyword
        already exists, it simply gets that keyword and associates it with the
        dataset.

        Should this be in the keywords app? I now have to add a remove keywords from
        dataset page as well.
    """
    account = get_object_or_404(Account, account_slug=account_slug)
    dataset = get_object_or_404(Dataset, dataset_slug=dataset_slug, account=account)
    keyword_list = dataset.keywords.all()
    # I don't like this... how can I do it better?
    if "kw" in request.POST:
        kw = request.POST["kw"]
        dataset.keywords.remove(kw)
        return redirect("datasets:dataset_detail",
                        account_slug=account.account_slug,
                        dataset_slug=dataset.dataset_slug)
    
    context = {"account": account, "dataset": dataset, "keyword_list": keyword_list}
    template_name = "datasets/remove_keyword_from_dataset.html"
    return render(request, template_name, context)


@login_required
def dataset_update(request, account_slug=None, dataset_slug=None):
    account = get_object_or_404(Account, account_slug=account_slug)
    dataset = get_object_or_404(Dataset, dataset_slug=dataset_slug, account=account)
    if request.user.id != account.user.id:
        return redirect("access_denied")
    else:
        if request.method == "POST":
            form = DatasetUpdateForm(request.POST, instance=dataset)
            if form.is_valid():
                updated_dataset = form.save(commit=False)
                updated_dataset.account = account
                updated_dataset.save(update_fields=[
                    "title", "author", "url",
                    "public_access", "description",
                    "dataset_slug"])

            return redirect("datasets:dataset_detail",
                            account_slug=account.account_slug,
                            dataset_slug=dataset.dataset_slug)
        else:
            form = DatasetUpdateForm(instance=dataset)
            template_name = "datasets/dataset_update.html"
        return render(request, template_name,
                      {"form": form,
                       "account": account,
                       "dataset": dataset})


@login_required
def dataset_update_auth(request, account_slug=None, dataset_slug=None):
    account = get_object_or_404(Account, account_slug=account_slug)
    dataset = get_object_or_404(Dataset, dataset_slug=dataset_slug, account=account)
    if request.user.id != account.user.id:
        return redirect("access_denied")
    else:
        if request.method == "POST":
            form = DatasetUpdateAuthForm(request.POST, instance=dataset)
            if form.is_valid():
                updated_dataset = form.save(commit=False)
                updated_dataset.account = account
                updated_dataset.save()

            return redirect("datasets:dataset_detail",
                            account_slug=account.account_slug,
                            dataset_slug=dataset.dataset_slug)
        else:
            form = DatasetUpdateAuthForm(instance=dataset)
            template_name = "datasets/dataset_update_auth.html"
        return render(request, template_name,
                      {"form": form,
                       "account": account,
                       "dataset": dataset})


@login_required
def dataset_remove(request, account_slug=None, dataset_slug=None):
    account = get_object_or_404(Account, account_slug=account_slug)
    dataset = get_object_or_404(Dataset, dataset_slug=dataset_slug, account=account)
    context = {"account": account, "dataset": dataset}
    template_name = "datasets/dataset_remove.html"
    if request.user.id != account.user.id:
        return redirect("access_denied")
    else:
        if request.method == "POST":

templates/datasets/add_keyword_to_dataset.html
{% extends "base.html" %}
{% block title %}New Keyword{% endblock title %}

{% block breadcrumbs %}
/ <a href="{{ account.get_absolute_url }}">{{ account.user }}</a>
/ <a href="{{ dataset.get_absolute_url }}">{{ dataset.title }}</a>
/ <a href="{% url 'datasets:add_keyword_to_dataset' account.account_slug dataset.dataset_slug %}">add keyword</a>
{% endblock breadcrumbs %}

{% block content %}
<div class="container">
  <h2>Add a keyword to {{ dataset.title }}</h2>
  <hr>
  <p>
    <form action="." method="POST">
      {% csrf_token %}
      <input type="text" placeholder="The new keyword goes here" name="kw">
    </form>
  </p>
</div>
{% endblock content %}

templates/datasets/dataset_create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_title %}Add Dataset{% endblock head_title %}

{% block content %}

<br/>
<h1 class="text-xs-center">Add Dataset</h1>
<hr class="divider">

  <div class="col-12 col-xs-12" id="dataset_create_form">
    <form action="." method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input id="submit_dataset" class="btn btn-success" type="submit" value="Submit">
    </form>
  </div>

{% endblock content %}

templates/datasets/dataset_detail.html
{% extends "base_portal.html" %}
{% load staticfiles %}

{% block title %}{{ dataset.title }}{% endblock title %}

{% block breadcrumbs %}
/ <a href="{{ account.get_absolute_url }}">{{ account.user }}</a>
/ <a href="{{ dataset.get_absolute_url }}">{{ dataset.title }}</a>
{% endblock breadcrumbs %}

{% block portal_content %}

<h1>{{ dataset.title }} page</h1>
<hr>
<h1>{% if request.user == account.user %}{{ request.user }}{% endif %}</h1>

<div class="row" id="main">
  <div class="col-xs-12">
    <p><b>Author:</b> {{ dataset.author }}</p>
    <p><b>Description:</b> {{ dataset.description }}</p>
    {% if keyword_list %}
    <p><b>Keywords:</b>
      {% for keyword in keyword_list %}
      <a href="{{ keyword.get_absolute_url }}">{{ keyword.keyword }}</a>, 
      {% endfor %}
    </p>
    {% endif %}

    {% if request.user == account.user %}
    <h4>
      <a href="{% url 'datasets:add_keyword_to_dataset' account.account_slug dataset.dataset_slug %}">
        Add a keyword to {{ dataset.title }}
      </a>
    </h4>
    <h4>
      {% if keyword_list %}
      <a href="{% url 'datasets:remove_keyword_from_dataset' account.account_slug dataset.dataset_slug %}">
        Remove a keyword from {{ dataset.title }}
      </a>
    </h4>
    {% endif %}

    <h4>
      <a href="{% url 'datasets:dataset_update' account.account_slug dataset.dataset_slug %}">
        Update Dataset Details
      </a>
    </h4>
    <h4>
      <a href="{% url 'datasets:dataset_update_auth' account.account_slug dataset.dataset_slug %}">
        Update Dataset Auth Details
      </a>
    </h4>
    <h4>
      <a href="{% url 'datasets:dataset_remove' account.account_slug dataset.dataset_slug %}">
        Remove Dataset
      </a>
    </h4>
    {% endif %}
    <hr />
    <h4>
      <a href="{% url 'datasets:embed_dataset' account.account_slug dataset.dataset_slug %}">
        * View map in full screen *
      </a>
    </h4>
    <hr />
  </div>
</div>
{% endblock portal_content %}

templates/datasets/dataset_detail_serialized.html
{% extends "base_portal.html" %}
{% load staticfiles %}


{% block title %}{{ dataset.title }}{% endblock title %}

{% block css %}

<style>

  #datasetsContainer {
    height: 50em;
    float: left;
  }

  #datasets-list {
    overflow-y: auto;
    height: 41em;
  }

  #mapContainer {
    float: right;
  }

  #mapid {
    height: 50em;
    margin-bottom: 10px;
  }

  #find_place_container {
    display: none;
  }

  #test_url_container {
    display: none;
  }

  /*
  #draw_polygon_container {
    display: none;
  }
  */

  #within_polygon_container {
    display: none;
  }

</style>

{% endblock css %}

{% block breadcrumbs %}
/ <a href="{{ account.get_absolute_url }}">{{ account.user }}</a>
/ <a href="{{ dataset.get_absolute_url }}">{{ dataset.title }}</a>
{% endblock breadcrumbs %}

{% block portal_content %}


<h1>{{ title }} page</h1>
<hr/>
<h1>
  {% if request.user == account.user %}
  {{ request.user }}
  {% endif %}
</h1>

<div class="row" id="main">
  <div class="col-xs-12">
    <p><b>Author:</b> {{ author }}</p>
    <p><b>Description:</b> {{ description }}</p>

    {% if request.user == account.user %}
    <h4>
      <a href="{% url 'datasets:dataset_update' account.account_slug dataset.dataset_slug dataset.pk %}">
        Update Dataset Details
      </a>
      <h4>
        <a href="{% url 'datasets:dataset_update_auth' account.account_slug dataset.dataset_slug dataset.pk %}">
          Update Dataset Auth Details
        </a>
        <h4>
          <a href="{% url 'datasets:dataset_remove' account.account_slug dataset.dataset_slug dataset.pk %}">
            Remove Dataset
          </a>
        </h4>
        {% endif %}


        <hr/>
  </div>
  <div>
    <h3>account slug: {{account_slug}}</h3>
    <h3>dataset slug: {{dataset_slug}}</h3>
  </div>


  <!-- this should be javascript from here -->
  <div class="col-xs-12" id="map-and-buttons">
    <div id="js-mount">
      <i class="fa fa-lg fa-spinner fa-spin"></i><br><br>
      <i class="pending">Loading...</i><br><br>  
    </div>
  </div>
  <div id="div1"></div>
  <!-- to here -->

  <script>
    json_data = JSON.parse("{{json_data|escapejs}}");
    js_mount = document.getElementById("js-mount");
  </script>
  <script src="{% static 'js/serialized.js' %}"></script>

{% endblock portal_content %}

templates/datasets/dataset_remove.html
{% extends "base.html" %}

{% block title %}Remove Dataset{% endblock title%}

{% block breadcrumbs %}
  / <a href="{{ account.get_absolute_url }}">{{ account.user }}</a>
  / <a href="{{ dataset.get_absolute_url }}">{{ dataset.title }}</a>
  / <a href="{% url 'datasets:dataset_remove' account.account_slug dataset.dataset_slug %}">remove</a>
{% endblock breadcrumbs %}

{% block content %}

  <p>
    <form id="confirm_remove_form" action="" method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="Yes, please remove {{ dataset.title }}"/>
    </form>
  </p>

  <p>
    <a href="{{ dataset.get_absolute_url }}">
      No, take me back to the {{ dataset.title }} page
    </a>
  </p>

{% endblock content %}

templates/datasets/dataset_update.html
{% extends "base.html" %}

{% block title %}Update {{ dataset.title }}{% endblock title %}

{% block breadcrumbs %}
  / <a href="{{ account.get_absolute_url }}">{{ account.user }}</a>
  / <a href="{{ dataset.get_absolute_url }}">{{ dataset.title }}</a>
  / <a href="{% url 'datasets:dataset_update' account.account_slug dataset.dataset_slug %}">update</a>
{% endblock breadcrumbs %}

{% block content %}

  <p>
    <form id="update_dataset_form" action="." method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-default" type="submit" value="Update {{ dataset.title }}">
    </form>
  </p>

  <p>
    <a href="{% url 'datasets:dataset_update_auth' account.account_slug dataset.dataset_slug %}">
      Update {{ dataset.title }} authentication details
    </a>
  </p>

  <p>
    <a href="{{ dataset.get_absolute_url }}">
      No, take me back to {{ dataset.title }}'s page
    </a>
  </p>

{% endblock content %}

templates/datasets/dataset_update_auth.html
{% extends "base.html" %}

{% block title %}Update {{ dataset.title }}{% endblock title %}

{% block breadcrumbs %}
  / <a href="{{ account.get_absolute_url }}">{{ account.user }}</a>
  / <a href="{{ dataset.get_absolute_url }}">{{ dataset.title }}</a>
  / <a href="{% url 'datasets:dataset_update_auth' account.account_slug dataset.dataset_slug %}">update authentication details</a>
{% endblock breadcrumbs %}

{% block content %}

  <p>
    <form action="." method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-default" type="submit" value="Update {{ dataset.title }}">
    </form>
  </p>

  <p>
    <a href="{% url 'datasets:dataset_update' account.account_slug dataset.dataset_slug %}">
      No, take me back to {{ dataset.title }}'s regular update page
    </a>
  </p>

  <p>
    <a href="{{ dataset.get_absolute_url }}">
      No, take me back to {{ dataset.title }}'s page
    </a>
  </p>

{% endblock content %}

templates/datasets/embed_dataset.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ZMT | {% block title %}{{ dataset.title }}{% endblock title%}</title>

    <link rel="shortcut icon" type="image/png" href="{% static 'images/zmt_favicon.ico' %}">

    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
    <link rel="stylesheet" href="{% static 'css/map.css' %}" />

    <style>
      .main-map, html, body {
        height: 100%;
        margin: 0;
      }

      .main-map {
        display: flex;

      }

      .dataset {
        display: none;
      }

      #mapid {
        height: 100%;
        width: 100%;
      }
    </style>

  </head>
  <body>
    <!-- NOSCRIPT -->
    <div class="container">
      <noscript>
        <h2>Warning: without javascript enabled this site will not show maps or retreive data. Also, the buttons will be broken and dataset links will not show up.</h2>
      </noscript>
    </div>
    <!-- END NOSCRIPT -->

    <div class="main-map">
      <div class="custom-popup" id="mapid"></div>
    </div>
    <div class="dataset">
      {% if dataset.dataset_password %}
        <div name="dataset" id="{{ dataset.pk }}" detail="yeah" value="{{ dataset.ext }}"></div>
      {% else %}
        <div name="dataset" id="{{ dataset.pk }}" detail="yeah" value="{{ dataset.ext }}" url="{{ dataset.url }}"></div>
      {% endif %}
    </div>

    <script src="{% static 'js/bundle.js' %}"></script>

  </body>
</html>

templates/datasets/new_dataset.html
{% extends "base.html" %}

{% block title %}New Dataset{% endblock title %}

{% block breadcrumbs %}
  / <a href="{{ account.get_absolute_url }}">{{ account.user }}</a>
  / <a href="{% url 'datasets:new_dataset' account.account_slug %}">new dataset</a>
{% endblock breadcrumbs %}

{% block content %}

  <div id="format_directions">
    <p>
      If you are adding a <b>csv dataset</b> please make sure that the <b>longitude and latitude columns are named "longitude" and "latitude" and spelled with lowercase letters</b>. Additionally the coordinates need to be written as <b>decimal degrees; e.g. 53.108, 8.845</b>. The degrees, minutes, seconds coordinate style, or any variations thereof, will not work with this website.
    </p>
    <p>
      <b>WARNING:</b> if you are using microsoft excel to create your .csv files be certain that you set the decimal separator to a dot "." and not a comma ",". The site will not be able to read gps coordinates that are not written this way. If you have a windows operating system follow this <b><a href="https://www.howtogeek.com/245510/how-to-change-excels-decimal-separators-from-periods-to-commas/" target="_blank">link</a></b> to see how to change the decimal separator to a dot, and if you are using a mac operating system follow this <b><a href="https://www.laurivan.com/change-decimal-comma-dot-excel-mac/" target="_blank">link</a></b>.
    </p>
    <p>
      If you are adding a dataset that is saved on Owncloud you will not need to enter anything in the <b>"Url" field</b>, and vis versa. Also, Owncloud path is case sensitive. 
    </p>
  </div>
  <hr/>
  <p>
    <form action="." method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-default" type="submit" value="Submit">
    </form>
  </p>

  <p>
    <a href="{{ account.get_absolute_url }}">
      No, take me back to {{ account.user }}'s page
    </a>
  </p>

{% endblock content %}

templates/datasets/remove_keyword_from_dataset.html
{% extends "base.html" %}

{% block title %}New Keyword{% endblock title %}

{% block breadcrumbs %}
/ <a href="{{ account.get_absolute_url }}">{{ account.user }}</a>
/ <a href="{{ dataset.get_absolute_url }}">{{ dataset.title }}</a>
/ <a href="{% url 'datasets:remove_keyword_from_dataset' account.account_slug dataset.dataset_slug %}">remove keyword</a>
{% endblock breadcrumbs %}

{% block content %}

<h2>Remove a keyword from {{ dataset.title }}</h2>
<hr>

      <p><b>Keywords:</b>

      <form action="." id="remove_keyword_form" method="post">
        <select name="kw">
          {% for keyword in keyword_list %}
            <option value="{{ keyword.pk }}">{{ keyword }}</option>
          {% endfor %}
        </select>
        {% csrf_token %}
        <input type="submit" value="submit">
      </form>
      </p>

{% endblock content %}