accounts/urls.py
from django.conf.urls import url

from accounts import views


app_name = "accounts"

urlpatterns = [

    url(r'^accounts/$',
        views.AccountList.as_view(),
        name="account_list"),

    url(r'^(?P<account_slug>[-\w]*)/$',
        views.account_detail,
        name="account_detail"),

    url(r'^(?P<account_slug>[-\w]*)/remove/$',
        views.account_remove,
        name="account_remove"),

    url(r'^(?P<account_slug>[-\w]*)/update/$',
        views.account_update,
        name="account_update"),
]

datasets/urls.py
from django.conf.urls import url

from datasets import views

app_name = "datasets"

urlpatterns = [
    url(r"^new_dataset/$",
        views.new_dataset,
        name="new_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/$",
        views.dataset_detail,
        name="dataset_detail"),

    url(r"^(?P<dataset_slug>[-\w]*)/embed/$",
        views.embed_dataset,
        name="embed_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/sanity/$",
        views.sanity_dataset,
        name="sanity_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/add_keyword/$",
        views.add_keyword_to_dataset,
        name="add_keyword_to_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/remove_keyword/$",
        views.remove_keyword_from_dataset,
        name="remove_keyword_from_dataset"),

    url(r"^(?P<dataset_slug>[-\w]*)/update/$",
        views.dataset_update,
        name="dataset_update"),

    url(r"^(?P<dataset_slug>[-\w]*)/update/auth/$",
        views.dataset_update_auth,
        name="dataset_update_auth"),

    url(r"^(?P<dataset_slug>[-\w]*)/remove/$",
        views.dataset_remove,
        name="dataset_remove"),
]

keywords/urls.py
from django.conf.urls import url

from keywords import views

app_name = "keywords"

urlpatterns = [
    url(r'^$',
        views.keyword_list,
        name="keyword_list"),

    url(r'^(?P<keyword_slug>[-\w]*)/$',
        views.keyword_detail,
        name="keyword_detail"),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView

from core.forms import CustomUserCreationForm

from main import views


urlpatterns = [

    url(r'^$',
        views.portal,
        name='portal'),

    url(r'^about/$',
        TemplateView.as_view(template_name='about.html'),
        name='about'),

    url(r'^access_denied/$',
        TemplateView.as_view(template_name='access_denied.html'),
        name='access_denied'),

    url(r'^admin/', admin.site.urls),

    url(r'^contact/$',
        TemplateView.as_view(template_name='contact.html'),
        name='contact'),

    url(r'^load_dataset/(?P<pk>[0-9]+)/$',  # this one is tricky
        views.load_dataset,
        name='load_dataset'),

    # should this be part of the accounts app, where I create an account?
    url(r'^register/',
        CreateView.as_view(
            template_name='register.html',
            form_class=CustomUserCreationForm,
            success_url='/login'
        ),
        name='register'),

    # django sign in forms and stuff
    url(r'^', include('django.contrib.auth.urls')),
    #
    # The default urls from django.contrib.auth.urls:
    # ^login/$ [name='login']
    # ^logout/$ [name='logout']
    # ^password_change/$ [name='password_change']
    # ^password_change/done/$ [name='password_change_done']
    # ^password_reset/$ [name='password_reset']
    # ^password_reset/done/$ [name='password_reset_done']
    # ^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/
    #     (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$
    #     [name='password_reset_confirm']
    # ^reset/done/$ [name='password_reset_complete']
    #
    # I also want to put create update delete user views in this part


    # I just removed django rest framework stuff
    # url(r'^api/',
    #    include('api.urls',
    #            namespace='api')),

    url(r'^keywords/',
        include('keywords.urls',
                namespace='keywords')),

    url(r'^',
        include('accounts.urls',
                namespace='accounts')),

    url(r'^(?P<account_slug>[-\w]*)/',
        include('datasets.urls',
                namespace='datasets')),
]

templates/about.html
{% extends "base.html" %}

{% block title %}About{% endblock title %}

{% block breadcrumbs %}
/ <a href="{% url 'about' %}" >about</a>
{% endblock breadcrumbs %}

{% block content %}
<p>
  Spatial Data Hub is a web application built for scientific researchers to explore, advertise, and share spatial research data without storing it in a specific database. Most research data tools are focused on data accessibility, as defined by the FAIR data principles (https://www.force11.org/group/fairgroup/fairprinciples). Spatial Data Hub is a data findability tool with the goal of becomming a top Geographic Information Systems (GIS) data displaying website. Work on Spatial Data Hub began in May 2016 and has continued since. However, lately the focus has shifted to preparing a scientific manuscript describing Spatial Data Hub for peer review and publication. The project is based out of the <a href="https://www.leibniz-zmt.de/en/" target="_blank">Leibniz Centre for Tropical Marine Research</a> in Bremen, Germany. We plan to keep the code behind the website as simple as possible, while staying up to date with the latest trends. Further functionality will be added as the project matures.
</p>
<p>
  If you would like to see the source code for the website visit our <a href="https://github.com/spatialdatahub/spatialdatahub.org" target="_blank">github page</a>.
</p>
<p>
  If you have any questions or comments regarding the website, please email Patrick Curry at patrick.curry(at)leibniz-zmt.de.
</p>
<p>This website is being developed with <a href="https://www.djangoproject.com/" target="_blank">
    Django</a>, 
  <a href="https://www.postgresql.org/" target="_blank">PostgreSQL</a>,
  <a href="http://leafletjs.com/" target="_blank">Leaflet</a>,
  and <a href="http://turfjs.org/" target="_blank">Turf</a>.
</p>
{% endblock content %}

templates/access_denied.html
{% extends "base.html" %}

{% block content %}
<h1>Sorry, you do not have access rights for this page.</h1>
<h3><a href="/">Return to portal</a></h3>
<h3><a href="/login/">Login</a></h3>
{% endblock content %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>ZMT | {% block title %}{% endblock title%}</title>

  <link rel="shortcut icon" type="image/png" href="{% static 'images/zmt_favicon.ico' %}">

  <!-- Latest compiled and minified CSS 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
-->
  <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>

  <!-- NEW HEADER / NAVBAR -->
  <header>
    <a href="https://www.leibniz-zmt.de/en/" terget="_blank">
      <img src="{% static 'images/zmt_logo_white.png' %}" height="32" alt="ZMT Logo" />
    </a>
    <a href="{% url 'portal' %}">Home</a>
    <a href="{% url 'accounts:account_list' %}">Accounts</a>
    <a href="{% url 'keywords:keyword_list' %}">Keywords</a>
    {% if user.is_authenticated %}
    <a href="{{ user.account.get_absolute_url }}">{{ user.account }}</a>
    <a href="{% url 'logout' %}?next=/">Logout</a>
    {% else %}
    <a href="{%url 'register' %}">Register</a>
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
  </header>
  <!-- END NAVBAR -->

  <!-- NOSCRIPT -->
  <div>
    <noscript>
      <h2>Warning: without javascript enabled this site will not show maps or retreive data. Also, the buttons will be
        broken and dataset links will not show up.</h2>
    </noscript>
  </div>
  <!-- END NOSCRIPT -->

  <div>
    <!-- All the pages should have breadcrumbs -->
    <div>
      <h4>
        <a href="{% url 'portal' %}">Home</a>
        {% block breadcrumbs %}{% endblock breadcrumbs %}
      </h4>
    </div>
    <hr />

    {% if user.is_authenticated %}
    <h4>
      <a href="{% url 'datasets:new_dataset' user.account.account_slug %}">
        * Add New Dataset *
      </a>
    </h4>
    <hr />
    {% endif %}

    {% block content %}
    {% endblock content %}
  </div>
  <!-- CONTENT -->

  <!-- FOOTER -->
  <hr />
  <footer>
    <a href="{% url 'about' %}">About</a>
    <a href="{% url 'contact' %}">Contact</a>
    <a href="https://github.com/spatialdatahub/spatialdatahub.org" target="_blank">GitHub</a>
  </footer>
  <!-- END FOOTER -->

  <!--
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap.native/2.0.10/bootstrap-native.min.js"></script>
    -->

</body>

</html>

templates/base_portal.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
<link rel="stylesheet" href="{% static 'css/base-portal.css' %}" />

<!-- marker cluster cdn -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.0.5/MarkerCluster.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.0.5/MarkerCluster.Default.css" />

{% block portal_content %}

{% endblock portal_content %}
<!-- extras buttons -->
<section class="extras-button-group">
  <button id="show_find_place_container_button" class="extras-button">
    Search for a location
  </button>
  <button id="show_test_url_container_button" class="extras-button">
    Test dataset at an open URL
  </button>
  <!--
  <button id="show_within_polygon_container_button" class="extras-button">
    Get data within a polygon
  </button>
  -->
  <button id="toggle_marker_clusters" class="extras-button">
    Cluster Points Markers
  </button>
</section>
<!-- end extra buttons -->

<!-- container for all the extra stuff -->
<section id="find_place_container">
  <br />
  <div id="nominatim">
    <div class="nominatim-title">Find a place</div>
    <div class="nominatim-description">
      The nominatim function uses the openstreetmap location search function. Enter the name of a place you want to
      search for, for example california, and hit enter. Then select the most appropriate result from the drop down
      menu.
    </div>
    <input id="place_input" class="nominatim-place-input"
     type="text" placeholder="Enter place name here">
    <select id="selector" class="nominatim-place-selector"></select>
    <input id="select_button" class="nominatim-place-select-button"
     type="submit" value="Add to map">
    <input id="place_toggle" class="nominatim-place-toggle-button"
     type="submit" value="Toggle place">
  </div>
  <br />
</section>

<section id="test_url_container">
  <br />
  <div class="test-url-grid">
    <div class="test-url-title">Test a URL</div>
    <input class="test-url-input" id="test_url_input" type="text" placeholder="Enter URL Here">
    <div for="test_url_input">
      Enter a full url that is linked to an open dataset without any cross origin issues into the input and hit enter
      to add it to the map. For example <a href="https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson"
        target="_blank">these earthquake data points</a> can be added to the map with this method.
    </div>
    <div id="test_urls">
      <button id="toggle_test_urls">Toggle test datasets</button>
    </div>
  </div>
  <br />
</section>

<!--
<section id="within_polygon_container">
  <input id="file_name_input" type="text" placeholder="Enter the file name here">
  <button id="save_button">Save to geojson file</button>
</section>
-->

<hr />

<section id="main">

  <div id="mapContainer">
    <div class="custom-popup" id="mapid"></div>
  </div>
  <div id="datasetsContainer">
    {% if dataset %}
      <div name="dataset" id="{{ dataset.pk }}" detail="yeah" value="{{ dataset.ext }}"
      {% if dataset.dataset_password %}

      {% else %}
      url="{{ dataset.url }}"
      {% endif %}
      ></div>
    {% endif %}

    {% if dataset_list %}
    <ul class="nav nav-pills nav-stacked">
      <li>
        <form action="." method="GET">
          <input name="q" type="text" title="Search Datasets" placeholder="Search title, account, author, keyword">
        </form>
      </li>
      <li>
        <button class="btn btn-default btn-block" id="clear_map">
          Clear Map
        </button>
      </li>
    </ul>
    {% else %}
      no
    {% endif %}
  </div>

</section>
<!--
  <div id="datasetsContainer">

    {% if dataset %}
    {% if dataset.dataset_password %}
    <div name="dataset" id="{{ dataset.pk }}" detail="yeah" value="{{ dataset.ext }}">
    </div>
    {% else %}
    <div name="dataset" id="{{ dataset.pk }}" detail="yeah" value="{{ dataset.ext }}" url="{{ dataset.url }}">
    </div>
    {% endif %}
    <div id="clear_map"></div>
    {% else %}


    {% if dataset_list %}
    <ul class="nav nav-pills nav-stacked">
      <li>
        <form action="." method="GET">
          <input name="q" type="text" title="Search Datasets" placeholder="Search title, account, author, keyword">
        </form>
      </li>
      <li>
        <button class="btn btn-default btn-block" id="clear_map">
          Clear Map
        </button>
      </li>
    </ul>


    <div id="dataset-scroll-list">
      {% for dataset in dataset_list %}
      {% if dataset.dataset_password %}
      <div class="btn-group btn-group-justified" role="group">
        <div class="btn-group" role="group">
          <button type="button" class="btn btn-default" name="dataset" id="{{ dataset.pk }}" value="{{ dataset.ext }}">
            {{ dataset.title }}
          </button>
        </div>
        <div class="btn-group" role="group">
          <a href="{{ dataset.get_absolute_url }}" type="button" class="btn">
            Dataset page
          </a>
        </div>
      </div>
      {% else %}
      <div class="btn-group btn-group-justified" role="group">
        <div class="btn-group" role="group">
          <button type="button" class="btn btn-default" name="dataset" id="{{ dataset.pk }}" value="{{ dataset.ext }}"
            url="{{ dataset.url }}">
            {{ dataset.title }}
          </button>
        </div>
        <div class="btn-group" role="group">
          <a href="{{ dataset.get_absolute_url }}" type="button" class="btn">
            Dataset page
          </a>
        </div>
      </div>
      {% endif %}
      {% endfor %}
      {% else %}
      <a style="color:red" href="{% url 'portal' %}">
        No datasets available. Clear Search.
      </a>
      {% endif %}


      {% endif %}
    </div>
  </div>

</section>
-->

<script src="{% static 'js/bundle.js' %}"></script>

{% endblock content %}

templates/base_portal_react.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}






 <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
   integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
   crossorigin=""/>
<link rel="stylesheet" href="{% static 'css/map.css' %}" />

<!-- marker cluster cdn -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.0.5/MarkerCluster.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.0.5/MarkerCluster.Default.css" />

{% block portal_content %}

{% endblock portal_content %}




<!-- javascript for portal pages -->

<script src="https://unpkg.com/easy-nominatim@1.0.3"></script>

<!-- javascript for portal pages -->

<!-- extra javascript specific to the page, shouldn't need this -->
{% block portal_js %}
{% endblock portal_js %}

{% endblock content %}

templates/contact.html
{% extends "base.html" %}

{% block title %}Contact{% endblock title %}

{% block breadcrumbs %}
/ <a href="{% url 'contact' %}" >contact</a>
{% endblock breadcrumbs %}

{% block content %}
<p>
  If you have any questions about the website, please email Patrick Curry at patrick.curry@leibniz-zmt.de or Nils Moosdorf at nils.moosdorf@leibniz-zmt.de.
</p>
{% endblock content %}

templates/portal.html
{% extends "base_portal.html" %}
{% load staticfiles %}

{% block title %}Portal{% endblock title %}

templates/portal_react.html
{% extends "base_portal_react.html" %}
{% load staticfiles %}

{% block title %}Portal{% endblock title %}

{% block css %}
<style>

  #datasetsContainer {
    height: 50em;
    float: left;
  }

  #datasetsContainerJS {
    height: 50em;
    float: left;
  }

  #datasets-list {
    overflow-y: auto;
    height: 41em;
  }

  #mapContainer {
    float: right;
  }

  #mapContainerJS {
    float: right;
  }

  #mapid {
    height: 50em;
    margin-bottom: 10px;
  }

  #find_place_container {
    display: none;
  }

  #test_url_container {
    display: none;
  }

  /*
  #draw_polygon_container {
    display: none;
  }
  */

  #within_polygon_container {
    display: none;
  }

</style>

{% endblock css %}

{% block portal_content %}

  {% include "pieces/editmap.html" %}

  <div id="react"></div>
  <!-- to here -->
  <script>
    window.json_data = JSON.parse("{{json_data|escapejs}}");
    window.react_mount = document.getElementById("react");
  </script>
  <script src="{% static 'js/reactify.js' %}"></script>



{% endblock portal_content %}

{% block portal_js %}
{% endblock portal_js %}

templates/portal_serialized.html
{% extends "base_portal.html" %}
{% load staticfiles %}

{% block title %}Portal{% endblock title %}

{% block css %}
<style>

  #datasetsContainer {
    height: 50em;
    float: left;
  }

  #datasetsContainerJS {
    height: 50em;
    float: left;
  }

  #datasets-list {
    overflow-y: auto;
    height: 41em;
  }

  #mapContainer {
    float: right;
  }

  #mapContainerJS {
    float: right;
  }

  #mapid {
    height: 50em;
    margin-bottom: 10px;
  }

  #find_place_container {
    display: none;
  }

  #test_url_container {
    display: none;
  }

  /*
  #draw_polygon_container {
    display: none;
  }
  */

  #within_polygon_container {
    display: none;
  }

</style>

{% endblock css %}

{% block portal_content %}

  {% include "pieces/editmap.html" %}

  <div id="js-mount"></div>
  <!-- to here -->
  <script>
    json_data = JSON.parse("{{json_data|escapejs}}");
    js_mount = document.getElementById("js-mount");
  </script>
  <script src="{% static 'js/serialized.js' %}"></script>



{% endblock portal_content %}

{% block portal_js %}
{% endblock portal_js %}

templates/register.html
{% extends "base.html" %}

{% block breadcrumbs %}
  / <a href="{% url 'register' %}" >register</a>
{% endblock breadcrumbs %}

{% block content %}

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-default" type="submit" value="Submit" />
  </form>

{% endblock content %}